[alias]
buildstd = [
  "build", 
  "-Z", "build-std=std,panic_abort",
  "-Z", "build-std-features=optimize_for_size,panic_immediate_abort",
  "--release"
]
bloatstd = [
  "bloat", 
  "-Z", "build-std=std,panic_abort",
  "-Z", "build-std-features=optimize_for_size,panic_immediate_abort",
  "--release"
]

[build]
rustflags = ["-Zlocation-detail=none", "-Zfmt-debug=none"] 
